M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date Cts 02 Mar 2024 15:14:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-02T15:14:04+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.711
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.175
%
G90
G05
T1
X21.793Y3.734
X25.959Y3.734
T2
X3.937Y9.269
X15.367Y9.269
T0
M30
