M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date Paz 03 Mar 2024 00:05:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-03T00:05:45+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.508
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.175
%
G90
G05
T1
X21.869Y3.556
X25.883Y3.556
T2
X3.937Y9.271
X15.367Y9.271
T0
M30
